#!/bin/bash

MODULE=tmu

SDIR=`pwd`
CFGDIR=$SDIR/config

#
#
# Run Viz
konsole -p tabtitle="Viz" -p TerminalRows=15 -p TerminalColumns=50 -e $SDIR/$MODULE.v
echo "Wait... "
sleep 2
echo "Done."

# Run Mod
konsole -p tabtitle="Mod" -p TerminalRows=15 -p TerminalColumns=50 -e $SDIR/$MODULE.m
echo "Wait... "
sleep 2
echo "Done."

#

wmctrl  -a "mc"
wmctrl  -a "Kvorum_V"

$SDIR/$MODULE.py $CFGDIR/env.ctl $CFGDIR/map.ctl $CFGDIR/agents.ctl

rosnode kill kvorum_v
rosnode kill kvorum_m
