#!/usr/bin/env python3
# coding: utf-8

"""
  Map to Ctl Converter
  Заодно он создает и прочие полезные вещи (launch-файл)
  05.05.2019, 04.12.2020, 05.03.2024, 08.01.2025
  Version 2.1
  LP 23.03.2025

"""

import sys, time, math, os
from kvorum2 import mapfile
from kvorum2.mapfile import ctl
import argparse

Title = "map2ctl 2.1"

def EvalObjects(f):
    print('#', ctl.title, file=f)
    print('#', file=f)
    print('# source:', ctl.mapname, file=f)
    print('# dimX = {} dimY = {} step_x = {:3.2f} step_y = {:3.2f}'.format(ctl.dimX, ctl.dimY, ctl.step_x, ctl.step_y), file=f)
    print('#', file=f)

    # Robots positions
    for i in range(ctl.RobotNum):
        ctl.RobotX[i] = int(ctl.RobotX[i]*ctl.step_x)
        ctl.RobotY[i] = int((ctl.num_lines-ctl.RobotY[i])*ctl.step_y)

    print(file=f)
    print('# Robots positions',file=f)
    print('_RobotNum_ =', ctl.RobotNum, file=f)
    print('_RobotX_ =', ctl.RobotX, file=f)
    print('_RobotY_ =', ctl.RobotY, file=f)
    print('_RobotA_ =', ctl.RobotA, file=f)

    print('\n', file=f)

    for e in ctl.OBJECTS:
        e[1] = ctl.num_lines - e[1]
        x = int(e[0]*ctl.step_x)
        y = int(e[1]*ctl.step_y)
        code = e[2]
        level = e[3]
        draw_text = e[4]
        if (code<=0) or (level is None): continue
        rad_x = int(ctl.rat_x*ctl.step_x)
        rad_y = int(ctl.rat_y*ctl.step_y)
        s = 'Env.SetRectangleField({}, {}, {}, {}, {}, {})'.format(x, y, x+rad_x, y+rad_y, level, code)
        print(s, file=f)

        if(draw_text):
            offs_x = 0
            offs_y = ctl.step_y
            s = 'Env.Text({}, {}, "{}")'.format(x+offs_x, int(y+offs_y), code)
            print(s, file=f)

        print(file=f)

def MakePlan(planname):
    f = open(planname, 'w', encoding='utf-8') if not planname is None else sys.stdout

    print('#', ctl.title, file=f)
    print('#', file=f)
    print('# source:', ctl.mapname, file=f)
    print('#', file=f)
    print(file=f)

    plist=[]
    for e in ctl.OBJECTS:
        x, y = e[0]*ctl.step_x, e[1]*ctl.step_y
        rad_x, rad_y = ctl.rat_x*ctl.step_x, ctl.rat_y*ctl.step_y
        x, y = int(x+rad_x/2.0), int(y+rad_y/2.0)
        code = e[2]
        level = e[3]
        if level=='gdic.LEVEL_IR':
            plist.append([str(code), x, y, None])

    plist = sorted(plist, key=lambda name: name[0])

    print('global CPLAN', file=f)
    print('CPLAN = [', file=f)
    for i in range(len(plist)):
        s = "  ['{}',{}, {}, {}]".format(plist[i][0],plist[i][1],plist[i][2],plist[i][3])
        print(s, file=f, end='')
        if i<len(plist)-1: print(',', file=f)
    print(']', file=f)

    f.close()

def MakeLaunch(launchname):
    if launchname is None: return
    f = open(launchname, 'w', encoding='utf-8')
    print(f'''<!--
===================================================================================
  This document was autogenerated by map2ctl from {ctl.mapname}
  EDITING THIS FILE BY HAND IS NOT RECOMMENDED
===================================================================================

  Запуск yarp13_kvorum_bridge_node
  Много аргументов

  roslaunch yarp13_kvorum_bridge.launch
  roslaunch yarp13_kvorum_bridge.launch compass:=-60
  roslaunch yarp13_kvorum_bridge.launch compass:=-60 rotvang:=0.075
    ...
-->

<launch>
  <arg name="compass" default="0" />

  <arg name="cspeed"  default="0.75" />
  <arg name="rotvlin" default="0.01" />
  <arg name="rotvang" default="0.1" />

  <arg name="cellsize" default="0.3" />
''', file=f)    

    for i in range(ctl.RobotNum):
        print(f'''    
  <node name="yarp13_kvorum_bridge_node{i+1}" pkg="yyctl" type="yarp13_kvorum_bridge.py" output="screen" args="--rid {i+1}">
    <param name="compass" type="int" value="$(arg compass)" />
    <param name="cspeed" type="double" value="$(arg cspeed)" />
    <param name="rotvlin" type="double" value="$(arg rotvlin)" />
    <param name="rotvang" type="double" value="$(arg rotvang)" />
    <param name="cellsize" type="double" value="$(arg cellsize)" />    
  </node>
''', file=f)    

    print('''    
</launch>
''', file=f)    
    
    f.close()

################################################################################
#
# main
#
################################################################################

def main(mapname, resname, envname, planname, launchfile):

    outf = open(resname, 'w', encoding='utf-8')

    mapfile.ReadMap(mapname)

    EvalObjects(outf)
    outf.close()

    MakePlan(planname)
    
    MakeLaunch(launchfile)
    
    # Создаем env
    outf = open(envname, 'w', encoding='utf-8')

    print('#', ctl.title, file=outf)
    print('# Параметры поля', file=outf)
    print('# Этот файл читается при создании объекта Env', file=outf)
    print(file=outf)

    print('# Ширина и высота окна отображения поля', file=outf)
    print('self.MAX_SCR_X =', ctl.env_scr_X, file=outf)
    print('self.MAX_SCR_Y =', ctl.env_scr_Y, file=outf)
    print(file=outf)

    print('# Размер поля', file=outf)
    print('self.DIM_X =', ctl.dimX, file=outf)
    print('self.DIM_Y =', ctl.dimY, file=outf)
    print(file=outf)

    print('# Флаг режима топологии тора', file=outf)
    print('self.UseTorusRegime =', ctl.env_torus, file=outf)
    print(file=outf)

    print('# Частота обработки', file=outf)
    print('self.Rate =', ctl.env_freq, file=outf)
    print(file=outf)

    outf.close()

if __name__ == '__main__':

    parser = argparse.ArgumentParser(prog = sys.argv[0], description = Title, epilog = '')

    parser.add_argument('--map', nargs='?', type=str, default=None, required=True, metavar = 'mapfile', help = 'input Kvorum map file')
    parser.add_argument('--ctl', nargs='?', type=str, default=None, required=True, metavar = 'ctlfile', help = 'output Kvorum ctl file')
    parser.add_argument('--env', nargs='?', type=str, default=None, required=True, metavar = 'envfile', help = 'output Kvorum env file')

    parser.add_argument('--plan', nargs='?', type=str, default=None, required=False, metavar = 'planfile', help = 'output Kvorum plan file')
    parser.add_argument('--launch', nargs='?', type=str, default=None, required=False, metavar = 'launchfile', help = 'output yarp13_kvorum_bridge.launch file')

    # Странный финт
    # Первый и два последних аргумента (__name, __log) не нужны
    # Сделан потому, что при запуске roslaunch добавляются агрументы "__name:=...", и "__log:=..."
    arglist = []
    for e in sys.argv:
        if e.find("__name:=")==0: continue
        if e.find("__log:=")==0: continue
        arglist.append(e)
    namespace = parser.parse_args(arglist[1:])

    main(namespace.map, namespace.ctl, namespace.env, namespace.plan, namespace.launch)
