# Sensors Field

# Arduino data
msg_ans/ans arddata

# Arduino registers
msg_ans/ans ardreg

# Arduino i2c-servers
msg_ans/ans ardi2c

# Arduino status
msg_ans/ans ardstatus

#  Pololu data
msg_ans/ans pll

# QRcode Data
msg_ans/ans qrc

# Face Detector Data
msg_ans/ans face

# Speech Command
msg_ans/ans spc

# User Command Ctl Data (ManCtl)
msg_ans/ans usrcmd

# Kinect slot
msg_ans/ans kslot

# Robot Cartesian coordinates
msg_crtcoord/crtcoord robotcoord
