#!/bin/bash

MODULE=hunt
SDIR=`pwd`
CFGDIR=$SDIR/config

#
#
# Run Viz
konsole -p tabtitle="Viz" -p TerminalRows=15 -p TerminalColumns=50 -e $SDIR/$MODULE.v
echo "Wait... "
sleep 2
echo "Done."

# Run Mod
konsole -p tabtitle="Mod" -p TerminalRows=15 -p TerminalColumns=50 -e $SDIR/$MODULE.m
echo "Wait... "
sleep 2
echo "Done."

#
#
#

CDIR=~/ros
rosrun swhunt swhunt $CDIR/etc/kvorum/robot.xml 50

#
rosnode kill kvorum_v
rosnode kill kvorum_m

