# Sensors Field

# Arduino data
msg_kvorum2/sdata arddata

# Arduino registers
msg_kvorum2/sdata ardreg

# Arduino i2c-servers
msg_kvorum2/sdata ardi2c

# Arduino status
msg_kvorum2/sdata ardstatus

#  Pololu data
msg_kvorum2/sdata pll

# QRcode Data
msg_kvorum2/sdata qrc

# Face Detector Data
msg_kvorum2/sdata face

# Speech Command
msg_kvorum2/sdata spc

# User Command Ctl Data (ManCtl)
msg_kvorum2/sdata usrcmd

# Kinect slot
msg_kvorum2/sdata kslot

# Robot Cartesian coordinates
msg_crtcoord/crtcoord robotcoord
