#!/bin/bash

SDIR=`pwd`
CFGDIR=~/ros/src/kvorum/mobilization_ants/config

PYTHONPATH=$PYTHONPATH:~/ros/src/kvorum/pylib

RUN()
{
  konsole --hold -p tabtitle="$1 -- $2" -p TerminalRows=27 -p TerminalColumns=91 -e rosrun $1 $2 $3 $4 $5 $6 $7 $8 $9
  echo "Wait... "
  sleep 2
  echo "Done."
}

#
# kvorum.v
#
RUN mobilization_ants ants.v

#
# kvorum_m
#
RUN mobilization_ants ants.m

#
#
#
wmctrl  -a "mc"
wmctrl  -a "Kvorum_V"

cd ~/ros

rosrun mobilization_ants simple_ants.py _robots_num:=1

rosnode kill kvorum_m
rosnode kill kvorum_v
