# coding: utf-8
import fsm_alternative as fsm_lib


class FsmSearch(fsm_lib.TAutomaton):
    def __init__(self):
        fsm_lib.TAutomaton.__init__(self, 'Search', ['Init', 'SrchG', 'Q1', 'Q2', 'Q3', 'R', 'T', 'PreT'], ['T', 'F'], 'Init')

        self.add_rule(fsm_lib.TRule('Init', 'SrchG', 'else', 'self.MAX_ALIVE = 200; self.T = 0; self.TTurn = 7; self.TGoFwd = 20;', 5))
        self.add_rule(fsm_lib.TRule('SrchG', 'SrchG', 'self.isGLeft(self.goal_id)', 'self.turnLeft()', 5))
        self.add_rule(fsm_lib.TRule('SrchG', 'SrchG', 'self.isGFwd(self.goal_id)', 'self.goFwd()', 3))
        self.add_rule(fsm_lib.TRule('SrchG', 'SrchG', 'self.isGRight(self.goal_id)', 'self.turnRight()', 4))
        self.add_rule(fsm_lib.TRule('SrchG', 'R', 'else', 'self.T = 0', 1))
        self.add_rule(fsm_lib.TRule('SrchG', 'Obstacle1', 'self.isObst()', 'self.inner_fsm = self.loadObstacleAvoidanceFSM()', 8))
        self.add_rule(fsm_lib.TRule('Obstacle1', 'Obstacle1', 'self.inner_fsm.status == self.inner_fsm.FSM_NOT_FINISHED', 'self.inner_fsm.step()', 8))
        self.add_rule(fsm_lib.TRule('Obstacle1', 'SrchG', 'else', 'pass', 8))
        self.add_rule(fsm_lib.TRule('SrchG', 'Ritual1', 'self.isNearGoal(self.goal_id)', 'self.inner_fsm = self.loadRitualFSM()', 1))
        self.add_rule(fsm_lib.TRule('Ritual1', 'Ritual1', 'self.inner_fsm.status == self.inner_fsm.FSM_NOT_FINISHED', 'self.inner_fsm.step()', 1))
        self.add_rule(fsm_lib.TRule('Ritual1', 'PreT', 'else', 'pass', 1))
        self.add_rule(fsm_lib.TRule('SrchG', 'PreT', 'self.steps_counter > self.MAX_ALIVE', 'None', 0))
        self.add_rule(fsm_lib.TRule('R', 'Q1', 'self.rand(6) == 0', 'None', 1))
        self.add_rule(fsm_lib.TRule('R', 'Q2', 'self.rand(6) == 1', 'None', 1))
        self.add_rule(fsm_lib.TRule('R', 'Q3', 'else', 'None', 1))
        self.add_rule(fsm_lib.TRule('R', 'PreT', 'self.steps_counter > self.MAX_ALIVE', 'None', 0))
        self.add_rule(fsm_lib.TRule('Q1', 'Q1', 'self.T < self.TTurn', 'self.turnLeft(); self.T += 1', 4))
        self.add_rule(fsm_lib.TRule('Q1', 'SrchG', 'self.isGLeft(self.goal_id) or self.isGRight(self.goal_id) or self.isGFwd(self.goal_id)', 'self.goStop()', 1))
        self.add_rule(fsm_lib.TRule('Q1', 'SrchG', 'self.T >= self.TTurn', 'self.goStop()', 2))
        self.add_rule(fsm_lib.TRule('Q1', 'Obstacle2', 'self.isObst()', 'self.inner_fsm = self.loadObstacleAvoidanceFSM()', 3))
        self.add_rule(fsm_lib.TRule('Obstacle2', 'Obstacle2', 'self.inner_fsm.status == self.inner_fsm.FSM_NOT_FINISHED', 'self.inner_fsm.step()', 3))
        self.add_rule(fsm_lib.TRule('Obstacle2', 'SrchG', 'else', 'pass', 3))
        self.add_rule(fsm_lib.TRule('Q1', 'PreT', 'self.steps_counter > self.MAX_ALIVE', 'None', 0))
        self.add_rule(fsm_lib.TRule('Q2', 'Q2', 'self.T < self.TTurn', 'self.turnRight(); self.T += 1', 4))
        self.add_rule(fsm_lib.TRule('Q2', 'SrchG', 'self.isGLeft(self.goal_id) or self.isGRight(self.goal_id) or self.isGFwd(self.goal_id)', 'self.goStop()', 1))
        self.add_rule(fsm_lib.TRule('Q2', 'SrchG', 'self.T >= self.TTurn', 'self.goStop()', 2))
        self.add_rule(fsm_lib.TRule('Q2', 'Obstacle3', 'self.isObst()', 'self.inner_fsm = self.loadObstacleAvoidanceFSM()', 3))
        self.add_rule(fsm_lib.TRule('Obstacle3', 'Obstacle3', 'self.inner_fsm.status == self.inner_fsm.FSM_NOT_FINISHED', 'self.inner_fsm.step()', 3))
        self.add_rule(fsm_lib.TRule('Obstacle3', 'SrchG', 'else', 'pass', 3))
        self.add_rule(fsm_lib.TRule('Q2', 'PreT', 'self.steps_counter > self.MAX_ALIVE', 'None', 0))
        self.add_rule(fsm_lib.TRule('Q3', 'Q3', 'self.T < self.TGoFwd', 'self.goFwd(); self.T += 1', 4))
        self.add_rule(fsm_lib.TRule('Q3', 'SrchG', 'self.isGLeft(self.goal_id) or self.isGRight(self.goal_id) or self.isGFwd(self.goal_id)', 'self.goStop()', 1))
        self.add_rule(fsm_lib.TRule('Q3', 'SrchG', 'self.T >= self.TGoFwd', 'self.goStop()', 2))
        self.add_rule(fsm_lib.TRule('Q3', 'Obstacle4', 'self.isObst()', 'self.inner_fsm = self.loadObstacleAvoidanceFSM()', 3))
        self.add_rule(fsm_lib.TRule('Obstacle4', 'Obstacle4', 'self.inner_fsm.status == self.inner_fsm.FSM_NOT_FINISHED', 'self.inner_fsm.step()', 3))
        self.add_rule(fsm_lib.TRule('Obstacle4', 'SrchG', 'else', 'pass', 3))
        self.add_rule(fsm_lib.TRule('Q3', 'PreT', 'self.steps_counter > self.MAX_ALIVE', 'None', 0))
        self.add_rule(fsm_lib.TRule('PreT', 'T', 'True', 'self.goStop()', 1))
